fn main() {
    let stroka_old = String::from(">Rosalind_3715
GGTAATGCGGCGGACTTTGGCCCTCGGGGCGTTATCGCGAGCGAACCGTTCGACCACGTT
AGAGGACGCCAACGTCAACATTATCACATCCGGGCTCACGAATAAAAGTTCTAAAAACAC
GAGCAGTACACTTAAACCCGAACAATTCATCGTGTGTACAAGTGCGCGGTGGCGCTCAGG
TTGCGAACGATCTACAATGCCATGCCACAGTAAAGATCCTAACTGAGCCGGGTTTCCAGC
GCAAAACTGACATCGCAGATATTATTGAGTGCAGAAGCGGGGTCAAACGGAACTAACACG
ACCGTCGGACTTAGCAGAGCACTAACTTCTGACGGAAACAAGTATAACTCAAGATTGTGT
ACCATTGGGACTGTTTGCGAATGGAGCAATTTATCTATCCTCAGTGTTTTAATGACTTGG
AGATTAGGTCAGTTGTGCGGCTCCCCCTACGTCGGGCGACTGTCCTCGCACTTATTGGCA
GATGTTGGTCAACAGCTAATACTGCGAATCAAACTATTCCCATCGGAAAGAATTTGAAAA
CATAACTGATTTCAACATAATCGAGGAAACGAGCTAGTTGTAACTCATCATCGGTCTAAA
TACGTATACTTTTCATTACCGACTAATGAAGAGTGACATTCGGTTTCATCTGGCCTAGTA
TTTCTACTTCGCGGCTGCTGTGATAACATGACCAAACGCTGCAACCATCACATACATATG
TTATCTATCCGAAGCGTTTGGCCAGGGTTCTGCCTGCAGATCGGGGTATTGCCGGTCGCG
TCCAACATACCAGGATAAGCATGAGATACTCCATAAGAATCTGCGTGGACTATTTAAGGC
TCCAACTACTGTTTGTTTTCTCC
>Rosalind_6371
TGACGCCCTCTTAAACTTACCAACGCCGCCCAGATAACTCCTTCCTAACCCGGCGGACAT
CATACCATAGGATATATGTTTACATTCAGAGTGTGCGGGAACAGTGATTCAGAGGGACCC
GTACCCGAACAACTCTTCCATTCGGTTGTAGACCTCGTAAATATGTGATCGGTAAACGCG
GCAGATCACGGATGATAAGAGGTGTGAAAATATGGCCCGCCATGGTATACCTATGTCTCA
AATTGCTGCCATTGGATGCGTGTCCAGACCGTTCGGCCCTTTCCTAGACAAACTCACACT
CGTCTTACTATCTCCACAATCGGGTCTTGCCGACGGTTTCGCGTGCGGCGGTGCTGCTGG
CTTCCATCCCCCATGTTTCGTCGCACATGGTCACAGCTCCGGTCCATCCCTTGATATCGA
GGACAGCCCCACACATGCACACAATCAAAGATTGCTCTTTCACCAAGCTTCAGTGGGCCG
TAATTATAACCAACCGTTTCTCCCCGAACCCGACGATAGCCACCGAAATGAGCTCCTGGT
TGCGTATGGTCCGTCTTACACTAGCTATCGCTTACGCTTTTCGCTCTGGGCGGTCCACTA
CGCGACCTTGAGGTTAGAGCGGCGGGCAGCCTATTCGACCTTACGGGCTCCGGTCCTGGG
CTTTCAGTACAGTGCCCCTTCAGATGAGAACGTAGTCGATTATTACTAACCCATTTTCCC
TTGTCAAATTGACGAGCGGTCCCGGTAAGCGGCTCCCCAACCTTATGAGACACTTCAACT
ACTTATGCATCCTCTGGGGATTTATAGGCCCTGCGGGTGAAGACTCAGCGAGCGTATGAC
TAGGACTGACGCAAGGTCAATAGATTCGTTCTTGATATTCAAGTGCTAGTTATGTGCTAG
CGGTATCCGCGCGGACAAAT
>Rosalind_9350
AAGAGCGTTAGGCTTCCATAGCGCGGTGTATTATTTTGCTGGTAATATCCCTGGTAGATC
ACCTCCGATATGGCAGTTAGTCAGGTTTGGAGCTGGCTTAGGGGTGTAATGGACGATTCA
GAAGCTTTACGCTGTGGCAATATACCGGTGTACCATGCCCTCAACCGGACTATCATGCTT
ACCAGGCCAATTCGGGCCGTCATAACGGTTCAATCCCTTTGGTTACCAAAATAATTAACC
TCGTAATAAGAAACAACACACGTGGTTGATTAGCTACGGCGGCGTCTACGAAGTATTTAA
CTTGTATACGAACGTCTGTTCAGTCTAGCACCTGTACTACAGCCTAAATAGCTGTCGCCA
ATGGGTCATAATAGACGCCTAATCTGCAGTTCTCTCACGATAGGGACAGCAGATTAGGGG
GCAACATACTGGCCCGCGCGGCAGAGTCAGTGGGCCTCATGATAGTACGCCCAGTCGACT
GACGTACGGCTAGACTCTGTGCACGCCCTCAAGATGGAATACGGCTTTTGATCCTATGGT
CAGTGAAAACGTTTCAGTGTGCTCCGGACCACCGGTGATGCAACGGCAGGATGCACAAAC
AATATGTGGAGACGGTCAGTTCTTTGTGTAGCATCCTACTAATTCAGCAGCTAGTCAAGC
GATTAATATGGCACACTGGGATTCTAGAGGTCAGTTCCCAGACTTATCATGTTCACAAAC
AGCATACTCGACAGATTCCACTTGTAATCGCGTCTGGAGCAGCCTCCATAATCTAAGGAG
TACGTCCAAGCGCAATCGGGAAACAAAGGCCCAAGGAGGTGCACCGTTATGTCAATTTCG
>Rosalind_1560
ATCAGGGGCCAGTCACACAATTCCTGCTCGCACCTTAGGGCAATACTATTCCGCACCCCC
GTGCCGTGCGCGCTCATAAGGTGGGCCTACAACCCCTGGTATGCATTTAAAGCAATGCAA
TAGTGGCCAAATCAATAATAAATCTGAGAAGACTACCGTCAACGGACTCTTGATCAGTCG
GTTAGACCATTCGAAGGGTTCACAAGGCAACCGGTGGCAGTTATACTCCTGAAGAAGATT
TGTTATGGAACGCTGGCTTCGGACCATTGGATGGTGGGACGATTAATGGAGCTATCAGGC
TGACTATACACTCATATCATTAGAACCTCGAAAGGCATCTCACGTGCCATATTGAATTTT
GTGACGATAGCTTTGTACATACACTTCGAACAAACCACCGTCTATTATGTAAGCAAACTT
ACCCCCATATGTCATCATGGATCCCGAAGTTGAGAGGCAAGACGGCCCCTGTAGAACAAC
GAAGGTGCACCGGAGGTCCACGAGTTCTAGTTATCGTGTTCGTTCATCATCATCTGTTAA
CAAGCACCTGTATAGTCGGTTGATCAGGGTGGTACGACGGATTGCAACCAGACATTTTCT
AAGCCAAAGCGGACTCTCGTCCCGTACCCAAGACACGGGCATCATCTCTTGCAGGACGCG
CTGGGGGTGCGCGGTGGGTGTAGAACGTTAAAATTGCACTTGGGGTATTCGCTGGATCGG
AGAGTCCCCTAGGAACAATGCTAGCGCTCTTATGCGCCACGATACCCGCAAAAGTAGACC
AACCGGTCGTACCCCGGCGACCCGACCTTCCTCGGAAGCTCTAACGGCGATCTGTGAATC
GGACCGTCCGAAATATCGCCGGTGTTGTTTTCCTGAGTACCGGGGGCCATTTTTAGATCT
TTCGCTATTTACATCGAGGGCGTGCAGCTG
>Rosalind_5649
GCCAGACTATACGGTCGCGAGGGAAGTCCTGTTACAGGCTGGCGGGTCGGCGTGCAAATT
GTTGACGTTTTACACAGGATCCTTCCACCTATGATACACAGGCCCACTGGGATGGTTTTA
TCTAATCGTCGACCATATAATGTAGTGAATTTAGTCGGACAGTACTCTGCAATATGTGTC
CATCTGCGTGTGTCGCCCGGTAGAGCCTACCAGGCTCGTCCCATATCAAGAAACAGGTAG
CTGTTTACGTGCTCACTGACTGATATAATCCTTTCCCGCATTATCTTAGACCGTAAATAA
CAGCATCTGCGACGGGGCCGGTAAACACTTCACCGTAAGCCATGATGCAGCTCCCATCGG
CTCTATACCATCTGGCGCTCCCTCACGCTAGGGTTGTCGCCCAACATTATGCTTAGTACT
TTAGTGTTGTCCTCTCGTGTAACAAGTCCTGCCGCTTTTCAGCCCCTTACTCCGCGAGCA
TTATTTTCAGGGTCTACCGTGCAATGAATTGCTAACTGCAAATGAGCGTAGGGATCTACG
TTCCACAACGGGCATAGCGTGACCAATATGTGGGACGGATATTGGGCATATTGAGTGACT
AGGGCAGTCCATCTGGGCAGTGCTCGGGGTTGCCTGACACTGATTACGATCTTACATAGA
TCGCCTACAACTGCCGATGTTGGGTTCCGTATGCACAACCATCCCTAGACCTCGGAATCA
CCCGCCCAGAAACAGGCTTCCGCAGGCCAACTGAGGTTTATTACAACCATTGCCTCATCT
TGATCTCAGTGAAACCGTACGTTTTTTCGATGCCTCTACGCGTCTGGTCCGCGATAGACG
TGGGCCCGGAAGGATCTCCTCAGCTTACGAAGGGGGTCGGTATGTCGCTTCACCTGGTGG
TGACCACCAACACGCTACGCTCTAACGCTCCATTAGCGGATTGAGACATTTTTCGTCTTG
ATCTGATATAACTACCAG>");


    let mut num_gc = 0;
    let mut num_agct = 0;
    let mut procen: f32 = 0.0;


    for i in 0..stroka_old.len(){
        if &stroka_old[i..i+1] == "C" {            
            num_gc = num_gc + 1;
            num_agct = num_agct + 1;
        } else if &stroka_old[i..i+1] == "G" {            
            num_gc = num_gc + 1;
            num_agct = num_agct + 1;
        } else if &stroka_old[i..i+1] == "T" {            
            num_agct = num_agct + 1;
        } else if &stroka_old[i..i+1] == "A" {            
            num_agct = num_agct + 1;
        } else if &stroka_old[i..i+1] == ">" {
            procen = 100.0 * num_gc as f32 / num_agct as f32;
            println!("{}", procen);
            println!("{}", &stroka_old[i+1..i+14]);
            num_agct = 0;
            num_gc = 0;
            procen = 0.0;
        }

    }
    println!("proc: {}", procen);
    println!("konec");
}
